# -*- coding: utf-8 -*-
"""Financeiro - Analisador viabilidade de projeto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Axcaur-rezRLIL-YzyvFUibQE4IY4wNl
"""

# Importa as bibliotecas necessárias
import pandas as pd
from io import StringIO
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# String que contém os dados da tabela
dados_str = """
ID do Projeto,Investimento Inicial (R$ Mil),Taxa de Juros (Anual %),Prazo de Retorno (Anos),Tamanho da Equipe,Risco (Baixo=1, Alto=5),Viável (0=Não, 1=Sim)
P01,100,8.0,4,5,2,1
P02,350,12.5,6,8,4,0
P03,50,6.0,3,3,1,1
P04,200,10.0,5,7,3,1
P05,500,15.0,7,12,5,0
P06,80,7.5,4,4,2,1
P07,150,11.0,5,6,3,0
P08,400,13.0,6,9,4,0
P09,120,8.5,4,5,2,1
P10,30,5.5,2,2,1,1
P11,250,9.5,5,7,3,1
P12,450,14.0,7,10,5,0
P13,90,7.0,3,4,2,1
P14,180,11.5,6,6,4,0
P15,60,6.5,3,3,1,1
"""

# Cria o DataFrame
df = pd.read_csv(StringIO(dados_str))

# CORREÇÃO: Renomear as colunas imediatamente para nomes simples e sem caracteres especiais
df.columns = [
    'ID_Projeto',
    'Investimento_Inicial_Mil',
    'Taxa_Juros_Anual',
    'Prazo_Retorno_Anos',
    'Tamanho_Equipe',
    'Risco',
    'Viabilidade'
]

print("--- DataFrame Importado e Colunas Corrigidas ---")
print(df.head())

print(f"Número atual de colunas no DataFrame: {df.shape[1]}")
print("Nomes atuais das colunas:")
print(df.columns.tolist())

# Importa as bibliotecas necessárias
import pandas as pd
from io import StringIO
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# String de dados SIMPLIFICADA no CABEÇALHO para evitar erros de leitura
dados_str_simplificado = """
ID_Projeto,Investimento_Inicial_Mil,Taxa_Juros_Anual,Prazo_Retorno_Anos,Tamanho_Equipe,Risco,Viabilidade
P01,100,8.0,4,5,2,1
P02,350,12.5,6,8,4,0
P03,50,6.0,3,3,1,1
P04,200,10.0,5,7,3,1
P05,500,15.0,7,12,5,0
P06,80,7.5,4,4,2,1
P07,150,11.0,5,6,3,0
P08,400,13.0,6,9,4,0
P09,120,8.5,4,5,2,1
P10,30,5.5,2,2,1,1
P11,250,9.5,5,7,3,1
P12,450,14.0,7,10,5,0
P13,90,7.0,3,4,2,1
P14,180,11.5,6,6,4,0
P15,60,6.5,3,3,1,1
"""

# Cria o DataFrame lendo a string já simplificada
df = pd.read_csv(StringIO(dados_str_simplificado))

# Verifica o resultado
print("--- DataFrame Importado com 7 Colunas Corretas ---")
print(f"Novo número de colunas: {df.shape[1]}") # Deve ser 7
print(df.head())

# Importa as bibliotecas necessárias para ML (se não importadas no bloco anterior)
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# A. Separação dos Dados
# Features (X) e Target (y)
X = df.drop(['ID_Projeto', 'Viabilidade'], axis=1)
y = df['Viabilidade']

# Divide os dados em treino e teste (70%/30%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print("\n--- Separação Concluída ---")
print(f"X_train (Treino de Features) shape: {X_train.shape}")

# B. Treinamento do Modelo
model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)

print("\n--- Treinamento Concluído com Sucesso! ✅ ---")

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. Fazer previsões no conjunto de TESTE
y_pred = model.predict(X_test)

# 2. Avaliar a Acurácia
acuracia = accuracy_score(y_test, y_pred)
print(f"\n--- Resultados da Avaliação ---")
print(f"Acurácia do Modelo: {acuracia:.2f}")

# 3. Gerar a Matriz de Confusão
print("\nMatriz de Confusão:")
print(confusion_matrix(y_test, y_pred))

# 4. Relatório de Classificação
print("\nRelatório de Classificação:")
print(classification_report(y_test, y_pred))

# Analisar a importância/peso das features
coeficientes = pd.Series(model.coef_[0], index=X.columns)

print("\n--- Coeficientes do Modelo (Importância das Features) ---")
print("Quanto maior o valor absoluto, mais importante.")
print("Sinal positivo = Aumenta a Viabilidade (1).")
print("Sinal negativo = Diminui a Viabilidade (0).")
print(coeficientes.sort_values(ascending=False))